### ISSUE TITLE
New Topic: Tooling Resources

### ISSUE THREAD

**Issue by QueenOfSquiggles** [godot-rust/book#22]
Hey (just was talking with @Bromeon on the discord)

I think adding a section dedicated to tooling available through godot-rust would be helpful for people who want to make plugins, tools, and such. For example a breakdown of `Engine` Singletons, `EditorPlugin`s, and simple type definitions.

I would be happy to work on this myself as it is something I am more passionate about. In the meantime, I've started a [small knowledge base wiki](https://queenofsquiggles.github.io/squiggles-brain/godot/godot-rust/accessing-editor-interface/) for myself so I can search through things that I "know" but may have forgotten.

I am open to suggestions, critiques, etc. 

Also I was tempted to open a new issue about this, but is there a style guide for the book that I should follow when writing? Without trying to follow a guide I tend towards less professional and more personal speech patterns.

**Comment by Bromeon** [comment]
That sounds great, and cool to hear you already started building a knowledge base! 🙂 

In the gdnative-book, we had a category called [Recipes](https://godot-rust.github.io/gdnative-book/recipes/index.html), which contains such topics.
We could maybe add the same thing here?

**Comment by QueenOfSquiggles** [comment]
I like the Recipes section there. I'd love to see something similar for GDExt. I only have my little little corner of knowledge, but if other people contributed their recipes it could be a super helpful thing for people learning godot-rust to get up and running (assuming they're not like me and literally learning Rust by learning godot-rust)
