### ISSUE TITLE
Reentrant &mut self calls breaks hello world example

### ISSUE THREAD

**Issue by daniellavoie** [godot-rust/book#24]
I am under the impression that https://github.com/godot-rust/gdext/pull/501 broke the Hello World example.

I am getting the following compilation error:

```
error[E0599]: no method named `rotate` found for struct `godot::prelude::Base` in the current scope
  --> src/godot/mod.rs:30:19
   |
30 |       self.sprite.rotate((self.angular_speed * delta) as f32);
   |                   ^^^^^^ method not found in `Base<Sprite2D>`
```

I'll submit a PR to the doc if I get through a solution.

**Comment by PgBiel** [comment]
Sounds like this will be fixed by https://github.com/godot-rust/book/pull/21

**Comment by daniellavoie** [comment]
Yes indeed ! Closing the issue. Thanks for pointing out

**Comment by PgBiel** [comment]
I believe it should be fine to keep the issue open (at least IMO), since technically the problem is still there, at least until the PR is merged.

**Comment by Bromeon** [comment]
I'll merge the PR today.

**Comment by Bromeon** [comment]
PR is merged.
