### ISSUE TITLE
MIT -> MPL-2.0 relicense

### ISSUE THREAD

**Issue by Bromeon** [godot-rust/book#6]
Since the license was changed to MPL-2.0 in accordance with the gdext main repo and its API docs, we need to get permission from existing book contributors to re-license their past contributions for the gdext parts, or rewrite their texts.

This issue is solely to collect approvals for the re-licensing process. For questions/discussion, please contact me on Discord. Off-topic comments and discussion in this issue will be removed.

Contributors, in alphabetical order:
  - [ ] @Local-Trash 
  - [x] @ogapo
  - [x] @RamziA961
  - [x] @RefinedDev
  - [x] @Supreeeme

Please copy-paste _**verbatim**_ the following statement into a reply to this issue, or express if you do not want to re-license (which would mean we need to remove your text). Thanks a lot! 😊 

> I license my past contributions to the godot-rust book under the dual MIT/MPL-2.0 license, allowing licensees to chose either at their option.

**Comment by ogapo** [comment]
I license my past contributions to the godot-rust book under the dual MIT/MPL-2.0 license, allowing licensees to chose either at their option.

**Comment by RamziA961** [comment]
I license my past contributions to the godot-rust book under the dual MIT/MPL-2.0 license, allowing licensees to chose either at their option.

**Comment by Supreeeme** [comment]
I license my past contributions to the godot-rust book under the dual MIT/MPL-2.0 license, allowing licensees to chose either at their option.

**Comment by RefinedDev** [comment]
I license my past contributions to the godot-rust book under the dual MIT/MPL-2.0 license, allowing licensees to chose either at their option.

**Comment by Bromeon** [comment]
@Local-Trash any update?

**Comment by Bromeon** [comment]
@Local-Trash?
Otherwise we'll need to remove your contributions to comply with MPL-2.

**Comment by Bromeon** [comment]
Thanks to everyone who complied! 👍 

Regarding Local-Trash, the only commit was 18b5c3cdd763fec5265211e3474f369802bcb296 from March 2023, which primarily added 2 files:
- `coding.md`, which has been completely replaced with the Hello World tutorial.
- `setup.md`, which still exists, but has been significantly overhauled since.

I think it's safe to say that there is no significant amount of work in MIT remaining.
